repos:
  - repo: https://github.com/srstevenson/nb-clean
    rev: 3.3.0
    hooks:
      - id: nb-clean
        args:
          - --remove-empty-cells
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.5
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
