repos:
  - repo: https://github.com/srstevenson/nb-clean
    rev: 4.0.1
    hooks:
      - id: nb-clean
        entry: uv run nb-clean clean
        args:
          - --remove-empty-cells
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.1
    hooks:
      # Run the linter.
      - id: ruff
        entry: uv run ruff check --force-exclude
        types_or: [python, pyi]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        entry: uv run ruff format --force-exclude
        types_or: [python, pyi]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.6
    hooks:
      - id: uv-lock
        entry: uv run uv lock
